// 006 testing exceptions

fun divide(firstNumber :Int ,secondNumber :Int):Int{
    return firstNumber/secondNumber
}